name: Build and Publish Fluent Plugin
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build plugin
        run: bundle exec fluent-gem build fluent-plugin-eventbridge.gemspec

      - name: Publish to RubyGems
        run: |
          gem push -k ${{ secrets.RUBYGEMS_API_KEY }} fluent-plugin-eventbridge-*.gem
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}

